SolarManager/Models/SuperUserEndOfShift.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperUserEndOfShift
    {
        public long id { get; set; }
        public string superUserId { get; set; }
        public Nullable<int> EOSPrintNumber { get; set; }
        public Nullable<System.DateTime> lastEOSDate { get; set; }
        public Nullable<int> subUserID { get; set; }
        public string EOSPrint { get; set; }
    
        public virtual SubUser SubUser { get; set; }
    }
}

SolarManager/Controllers/SuperUserEndOfShiftsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolarManager.Models;
using Microsoft.AspNet.Identity;
using NLog;
using Thinktecture.IdentityModel.Mvc;

namespace SolarManager.Controllers
{
    [ResourceAuthorize("read", "SuperUserEndOfShift")]
    public class SuperUserEndOfShiftsController : Controller
    {
        private Logger _log = LogManager.GetCurrentClassLogger();

        private FlashPortalDBEntities db = new FlashPortalDBEntities();

        // GET: SuperUserEndOfShifts
        public async Task<ActionResult> Index()
        {
            var currentUserID = User.Identity.GetUserId();//UserID of Logged User
            try
            {
                var superUserEndOfShifts = (from spEos in db.SuperUserEndOfShifts.Include(s => s.SubUser)
                                                //.Where(spEos => spEos.superUserId == currentUserID)
                                            select spEos);

                //var superUserEndOfShifts = db.SuperUserEndOfShifts.Include(s => s.SubUser);
                return View(await superUserEndOfShifts.ToListAsync());
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                ViewBag.ErrorMessage = ex.Message;
                return View("Error");
            }
        }

        // GET: subUserTransaction/Transactions/1
        public async Task<ActionResult> Transactions(long? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                //Logged User
                var currentUserID = User.Identity.GetUserId();

                var eosObj = db.SuperUserEndOfShifts.Where(eos => eos.id == id)
                    .Select(eos => new
                    {
                        EOSPrintNumber = eos.EOSPrintNumber,
                    //subUserID = eos.subUserID,
                }).Single();

                var transactions = (from trn in db.SubUserTransactions.Include(s => s.SubUser)
                                    .Where(trn => trn.txEoSNumber == eosObj.EOSPrintNumber
                                    //&& (trn.subUserId == eosObj.subUserID))
                                    && (db.SubUsers.Any(sb => sb.UserID == currentUserID &&
                                    sb.SubUserID == trn.subUserId)))
                                    select trn);

                return View(await transactions.ToListAsync());
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                ViewBag.ErrorMessage = ex.Message;
                return View("Error");
            }
        }

        // GET: SuperUserEndOfShifts/Details/5        
        public async Task<ActionResult> EOSPrint(int id)
        {
            SuperUserEndOfShift superUserEndOfShift = await db.SuperUserEndOfShifts.FindAsync(id);

            //SuperUserEndOfShift superUserEndOfShift = await db.SuperUserEndOfShifts.FindAsync(id);
            return View("EOSPrint", superUserEndOfShift);
        }

        public async Task<ActionResult> EOSPopup(int id)
        {
            SuperUserEndOfShift superUserEndOfShift = await db.SuperUserEndOfShifts.FindAsync(id);
            if (superUserEndOfShift != null)
            {
                if (Request.IsAjaxRequest())
                {
                    return View("_EOSPrint", superUserEndOfShift);
                }
                else
                {
                    return View("EOSPrint", superUserEndOfShift);
                }
            }
            return View("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SolarManager/Views/SuperUserEndOfShifts/Create.cshtml
@model SolarManager.Models.SuperUserEndOfShift

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SuperUserEndOfShift</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.superUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.superUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.superUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EOSPrintNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EOSPrintNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EOSPrintNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastEOSDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastEOSDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastEOSDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subUserID, "subUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("subUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.subUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EOSPrint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EOSPrint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EOSPrint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolarManager/Views/SuperUserEndOfShifts/Delete.cshtml
@model SolarManager.Models.SuperUserEndOfShift

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SuperUserEndOfShift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.superUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.superUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EOSPrintNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EOSPrintNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastEOSDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastEOSDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EOSPrint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EOSPrint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubUser.SubUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubUser.SubUserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SolarManager/Views/SuperUserEndOfShifts/Details.cshtml
@model SolarManager.Models.SuperUserEndOfShift

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SuperUserEndOfShift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.superUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.superUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EOSPrintNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EOSPrintNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastEOSDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastEOSDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EOSPrint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EOSPrint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubUser.SubUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubUser.SubUserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SolarManager/Views/SuperUserEndOfShifts/EOSPopup.cshtml
@model SolarManager.Models.SuperUserEndOfShift

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EOSPopup</title>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
      $( function() {
        $( ".dialog" ).dialog();
      } );
    </script>

</head>
<body>
    <div id="dialog">
        <div>
            <h4>SuperUserEndOfShift</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.EOSPrint)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EOSPrint)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</body>
</html>

SolarManager/Views/SuperUserEndOfShifts/EOSPrint.cshtml
@model SolarManager.Models.SuperUserEndOfShift

@{
    ViewBag.Title = "EOSPrint";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EOSPrint</h2>

<div>
    <h4>SuperUserEndOfShift</h4>
    <hr />
    <dl class="dl-horizontal">        
        <dt>
            @Html.DisplayNameFor(model => model.EOSPrint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EOSPrint)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SolarManager/Views/SuperUserEndOfShifts/Edit.cshtml
@model SolarManager.Models.SuperUserEndOfShift

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SuperUserEndOfShift</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.superUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.superUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.superUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EOSPrintNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EOSPrintNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EOSPrintNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastEOSDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastEOSDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastEOSDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subUserID, "subUserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("subUserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.subUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EOSPrint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EOSPrint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EOSPrint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolarManager/Views/SuperUserEndOfShifts/Index.cshtml
@model IEnumerable<SolarManager.Models.SuperUserEndOfShift>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table" align="center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EOSPrintNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastEOSDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubUser.SubUserName)
        </th>
        <th>
            View Transactions
        </th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EOSPrintNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastEOSDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubUser.SubUserName)
            </td>
            <td>
                @Html.ActionLink("View Txns", "Transactions", new { id = item.id }) |
                @Html.ActionLink("EOS Print", "EOSPrint", new { id = item.id }) |
                @Html.ActionLink("EOS ModalPopup", "EOSPopup", new { id = item.id }, new { @class = "dialog" })@*"viewDialog" })*@
            </td>
        </tr>
    }
</table>

SolarManager/Views/SuperUserEndOfShifts/Indexx.cshtml
@model IEnumerable<SolarManager.Models.SuperUserEndOfShift>

@{
    Layout = null;
}

<h2>
    <br />
</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EOSPrintNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastEOSDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubUser.SubUserName)
        </th>
        <th>
            View Transactions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EOSPrintNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastEOSDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubUser.SubUserName)
            </td>
            <td>
                @Html.ActionLink("View Txns", "Transactions", new { id = item.id }) |
                @Html.ActionLink("EOS Print", "EOSPrint", new { id = item.id })
                @Html.ActionLink("EOS ModalPopup", "EOSPopup", new { id = item.id }, new { })
            </td>
        </tr>    }
</table>

@section scripts
{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <script type="text/javascript">
        $(function () {
            $("#ClickMeToShowDialog").click(function () {
                $("#dialog").css("display", "block");//show the dialog div
                $('#dialog').dialog({
                    width: 400,
                    height: 500,
                    resizable: false,
                    title: 'End Of Shift',
                    modal: true,
                    href: '@Url.Action("EOSDetail","SuperUserEndOfShifts")',//show the partial view
                    buttons: {
                        "Close": function () {
                            $(this).dialog("close");
                        }
                    }
                });
            });
        });
    </script>

<script type="text/javascript" language="javascript">

    $(document).ready(function () {


    $("#btnCreate").click(function () {
        InitializeDialog($("#departmentdialog"));

       $("#departmentdialog").dialog("open");
    });
    
    //Method to Initialize the DialogBox
    function InitializeDialog($element) {


        $element.dialog({
            autoOpen: false,
            width: 400,
            resizable: true,
            draggable: true,
            title: "End Of Shift",
            model: true,
            show: 'slide',
            closeText: 'x',
            dialogClass: 'alert',
            closeOnEscape: true,
            open: function (event, ui) {
                //Load the Partial View Here using Controller and Action
                $element.load('/SuperUserEndOfShifts/EOSPrint');
            },

            close: function () {
                $(this).dialog('close');
            }

        });

    }
});


</script>

}

SolarManager/Views/SuperUserEndOfShifts/Indexxx.cshtml
@model IEnumerable<SolarManager.Models.SuperUserEndOfShift>

@{
    ViewBag.Title = "Index";
}
<h2>
    <br />
</h2>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    

    @"~/Views/Shared/_Layout.cshtml"
    @Html.ActionLink("Crnizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
    $(document).ready(function () {

        $.ajaxSetup({ cache: false });

        $(".viewDialog").live("click", function (e) {
            var url = $(this).attr('href');
            $("#dialog-view").dialog({
                title: 'View Customer',
                autoOpen: false,
                resizable: false,
                height: 355,
                width: 400,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                open: function (event, ui) {
                    $(this).load(url);

                },
                buttons: {
                    "Close": function () {
                        $(this).dialog("close");

                    }
                },
                close: function (event, ui) {
                    $(this).dialog('close');
                }
            });

            $("#dialog-view").dialog('open');
            return false;
        });
    });
    </script>

</head>
<body>
    <div>
    <table class="table" align="center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EOSPrintNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lastEOSDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubUser.SubUserName)
            </th>
            <th>
                View Transactions
            </th>
        </tr>

        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EOSPrintNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lastEOSDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubUser.SubUserName)
                </td>
                <td>
                    @Html.ActionLink("View Txns", "Transactions", new { id = item.id }) |
                    @Html.ActionLink("EOS Print", "EOSPrint", new { id = item.id }) |
                    @Html.ActionLink("EOS ModalPopup", "EOSPopup", new { id = item.id }, new { @class = "dialog" })@*"viewDialog" })*@
                </td>
            </tr>
        }
    </table>
        </div>

    <div id="dialog-view" style="display: none">
    </div>
</body>
</html>

SolarManager/Views/SuperUserEndOfShifts/Transactions.cshtml
@model IEnumerable<SolarManager.Models.SubUserTransaction>

@{
    ViewBag.Title = "Transactions";
}

<h2>Transactions</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.txProduct)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.txAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.txStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.txDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.txEoSNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.txGUID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.txSubcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubUser.SubUserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.txProduct)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.txAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.txStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.txDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.txEoSNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.txGUID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.txSubcode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubUser.SubUserName)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.txRef }) |
            @Html.ActionLink("Details", "Details", new { id=item.txRef }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.txRef })
        </td>*@
    </tr>
}

</table>

SolarManager/Views/SuperUserEndOfShifts/_EOSPopup.cshtml
@model SolarManager.Models.SuperUserEndOfShift

<div>
    <h4>SuperUserEndOfShift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EOSPrint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EOSPrint)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>